version: "3.9"
services:
  app:
    build: .
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --workers 1"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
