"""Add age to users

Revision ID: b08bf7387745
Revises: 435273bf3ae1
Create Date: 2023-02-20 22:23:33.855795

"""
import sqlalchemy as sa
import sqlmodel  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision = "b08bf7387745"
down_revision = "435273bf3ae1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("age", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "age")
    # ### end Alembic commands ###
