name: Set Project for issues

on:
  issues:
    types: [opened]

jobs:
  set_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate token for GitHub App
        id: generate-token
        uses: getsentry/action-github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}

      - run: gh issue edit ${{ github.event.issue.number }} --add-project energy_prime
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
