name: Set Project for issues

on:
  issues:
    types: [opened]

jobs:
  set_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}

      - run: gh issue edit ${{ github.event.issue.number }} --add-project 2
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
