name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: release-${{ github.ref }}

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    name: Release on github
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build and publish
        run: |
          poetry build --format wheel

      # - name: Create Release
      #   run: gh release create ${{ github.ref }} --title ${{ github.ref }} --notes "Release ${{ github.ref }}" dist/*.whl
      #   env:
      #     GH_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  generate-client:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - run: npm install @openapitools/openapi-generator-cli -g
      - run: poetry run python energy_prime_back/generate_client.py
      - run: npx @openapitools/openapi-generator-cli generate -i openapi.json -g typescript-node -o ./client-generated

      - uses: actions/upload-artifact@v2
        with:
          name: client-generated
          path: ./client-generated

      - name: Generate token for GitHub App
        id: generate-token
        uses: getsentry/action-github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_KEY }}

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ steps.generate-token.outputs.token }}
        with:
          source-directory: client-generated
          destination-github-username: DemyCode
          destination-repository-name: energy-prime-ts-client
          user-email: verycols@gmail.com
          target-branch: master
